[hotfix][unwind_native] optimize the instruction count of the unwind_…
open-telemetry/opentelemetry-ebpf-profiler pull request #131
Opened 2024-08-22 10:06 UTC by tsint

Older kernels (such as 4.19) do not allow the instruction count of BPF programs to exceed 4096. However, as shown below, the latest version of the unwind_native program already has 4139 instructions.
```
.text has 0 instructions
perf_event/unwind_dotnet has 3591 instructions
perf_event/unwind_hotspot has 3073 instructions
tracepoint/sched/sched_switch has 1155 instructions
tracepoint/syscalls/sys_enter_read has 22 instructions
perf_event/unwind_stop has 445 instructions
perf_event/native_tracer_entry has 432 instructions
perf_event/unwind_native has 4139 instructions
perf_event/unwind_perl has 2777 instructions
perf_event/unwind_php has 2583 instructions
perf_event/unwind_python has 3778 instructions
perf_event/unwind_ruby has 3258 instructions
tracepoint/sched/sched_process_exit has 111 instructions
tracepoint/syscalls/sys_enter_bpf has 25 instructions
raw_tracepoint/sys_enter has 29 instructions
perf_event/unwind_v8 has 3337 instructions

Total instructions: 28755
```
Without modifying the logic of the unwind_native program, I optimized the instruction count of the unwind_native program to fit within the 4096 limit.

2024-08-22 10:16 UTC, florianl commented
hi @tsint 
And thank you for your contribution! Can you provide some information on how you compiled the eBPF programs that resulted in these increased instruction counts?

When checking the instruction count for the checked in eBPF blobs, we get the following at the moment:
```
$ ./print_instruction_count.sh tracer.ebpf.amd64 
/usr/bin/llvm-objdump

Instruction counts for tracer.ebpf.amd64:

.text has 0 instructions
perf_event/unwind_dotnet has 3597 instructions
perf_event/unwind_hotspot has 3073 instructions
tracepoint/sched/sched_switch has 1160 instructions
tracepoint/syscalls/sys_enter_read has 22 instructions
perf_event/unwind_stop has 445 instructions
perf_event/native_tracer_entry has 431 instructions
perf_event/unwind_native has 3995 instructions
perf_event/unwind_perl has 2646 instructions
perf_event/unwind_php has 2563 instructions
perf_event/unwind_python has 3739 instructions
perf_event/unwind_ruby has 3255 instructions
tracepoint/sched/sched_process_exit has 111 instructions
tracepoint/syscalls/sys_enter_bpf has 25 instructions
raw_tracepoint/sys_enter has 29 instructions
perf_event/unwind_v8 has 3317 instructions

Total instructions: 28408
```

With these eBPF blobs we do not have eBPF programs with more than 4096 instructions. There is also [a CI check in place](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/main/.github/workflows/unit-test-on-pull-request.yml#L78), to make sure this limit of instructions is respected and eBPF programs load on Linux kernel 4.19 - [see example run here.](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/actions/runs/10493825873/job/29068780034).

2024-08-22 11:51 UTC, tsint commented
Sorry, this might be because I used llvm-14 for compilation, which caused the generated BPF program to exceed 4096 instructions.

2024-08-22 16:56 UTC, rockdaboot commented
Thank you @tsint
Can you sign the CLA and add the two ebpf binaries built with clang-16 to this PR?
```
support/ebpf/tracer.ebpf.amd64
support/ebpf/tracer.ebpf.arm64
```
If that is a problem, let us know and we take care.

@florianl With clang-16, this PR shaves off some instructions:
amd64: 3995 -> 3971
arm64: 4060 -> 4025

2024-08-23 01:39 UTC, tsint commented
@rockdaboot 
OK, I'll try compiling and building with clang-16. Please wait for my test results.

2024-08-23 03:18 UTC, tsint commented
@rockdaboot 
Hello, I recompiled using clang-16 and have added two EBPF binary files to this PR.

2024-08-23 06:42 UTC, rockdaboot approved these changes
Thanks, LGTM

We have to improve the CI yet to automatically build/check the ebpf blobs :)

2024-08-23 07:15 UTC, fabled requested changes
Simplification looks great thanks! The error path metric incrementing needs adjustment and probably that shaves even more bytes out.

2024-08-23 07:15 UTC, fabled commented on support/ebpf/native_stack_trace.ebpf.c
> +    increment_metric(state->error_metric);
This should be removed. The error path ends up going to `unwind_stop` which does the increment also at https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/main/support/ebpf/interpreter_dispatcher.ebpf.c#L210

2024-08-23 07:15 UTC, fabled commented on support/ebpf/native_stack_trace.ebpf.c
> +    increment_metric(state->error_metric);
Same here. The error path handler does automatic `error_metric` incremenet.

2024-08-23 07:49 UTC, tsint commented
@fabled 
OK, I have removed those two lines of code in the PR based on your feedback. Thanks!

2024-08-26 08:47 UTC, christos68k approved these changes

2024-08-26 12:37 UTC, fabled approved these changes
LGTM

2024-08-27 05:56 UTC, merged